# Generated by Django 4.2.16 on 2024-10-13 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('danceability', models.DecimalField(decimal_places=4, max_digits=6)),
                ('energy', models.DecimalField(decimal_places=6, max_digits=8)),
                ('key', models.IntegerField()),
                ('loudness', models.DecimalField(decimal_places=6, max_digits=8)),
                ('mode', models.IntegerField()),
                ('acousticness', models.DecimalField(decimal_places=6, max_digits=8)),
                ('instrumentalness', models.DecimalField(decimal_places=8, max_digits=10)),
                ('liveness', models.DecimalField(decimal_places=6, max_digits=8)),
                ('valence', models.DecimalField(decimal_places=6, max_digits=8)),
                ('tempo', models.DecimalField(decimal_places=4, max_digits=8)),
                ('duration_ms', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('num_bars', models.IntegerField()),
                ('num_sections', models.IntegerField()),
                ('num_segments', models.IntegerField()),
                ('classification', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Song',
                'verbose_name_plural': 'Songs',
            },
        ),
        migrations.CreateModel(
            name='UserSongsRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Bad'), (3, 'Neutral'), (4, 'Good'), (5, 'Very Good')])),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songs.songs')),
            ],
        ),
    ]
